version: '3.3'
services:
  master: 
    image: tikazyq/crawlab:latest
    restart: always
    volumes:
      - /home/yeqing/config.py:/opt/crawlab/crawlab/config/config.py # 后端配置文件
      - /home/yeqing/.env.production:/opt/crawlab/frontend/.env.production # 前端配置文件
    ports:    
      - "8080:8080" # nginx
      - "8000:8000" # app
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
